-- Name: Wallace Tyner
-- Course: SDC250L
-- Assignment: Project 3.2 – Adding Referential Integrity

-- Question 1: Add foreign key constraints to ORDERS, REVIEWS, USERLIBRARY

ALTER TABLE ORDERS
ADD CONSTRAINT fk_orders_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);

ALTER TABLE ORDERS
ADD CONSTRAINT fk_orders_product
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTLIST(PRODUCTCODE);

ALTER TABLE REVIEWS
ADD CONSTRAINT fk_reviews_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);

ALTER TABLE REVIEWS
ADD CONSTRAINT fk_reviews_product
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTLIST(PRODUCTCODE);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT fk_userlibrary_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT fk_userlibrary_product
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTLIST(PRODUCTCODE);



-- Question 2: Users at least 18 years old

SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME,
       USERNAME
FROM USERBASE
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, DATEOFBIRTH)/12) >= 18;



-- Question 3: Max and average username length

SELECT MAX(LENGTH(USERNAME)) AS MAX_USERNAME_LENGTH,
       AVG(LENGTH(USERNAME)) AS AVG_USERNAME_LENGTH
FROM USERBASE;



-- Question 4: Security questions starting with What is / What was

SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'What is%'
   OR QUESTION LIKE 'What was%';



-- Question 5: Lowest rating and review count per product

SELECT PRODUCTCODE,
       MIN(RATING) AS LOWEST_RATING,
       COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY REVIEW_COUNT DESC;



-- Question 6: Products ranked at position 1

SELECT PRODUCTCODE,
       COUNT(*) AS USERS_RANKED_FIRST
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;



-- Question 7: Total spent per user

SELECT USERID,
       SUM(TOTALAMOUNT) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID;



-- Question 8: Gross profits by purchase date

SELECT PURCHASEDATE,
       SUM(TOTALAMOUNT) AS GROSS_PROFIT
FROM ORDERS
GROUP BY PURCHASEDATE
ORDER BY GROSS_PROFIT DESC;



-- Question 9: Top 5 games by hours played

SELECT *
FROM (
    SELECT PRODUCTCODE,
           SUM(HOURSPLAYED) AS TOTAL_HOURS
    FROM USERLIBRARY
    GROUP BY PRODUCTCODE
    ORDER BY TOTAL_HOURS DESC
)
WHERE ROWNUM <= 5;



-- Question 10: View of infractions per user

CREATE OR REPLACE VIEW view_user_infractions AS
SELECT USERID,
       COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID
ORDER BY INFRACTION_COUNT DESC;



-- Question 11: View of repeated rule violations

CREATE OR REPLACE VIEW view_rule_breaks AS
SELECT USERID,
       RULENUM,
       COUNT(*) AS TIMES_BROKEN
FROM INFRACTIONS
GROUP BY USERID, RULENUM
ORDER BY USERID;



-- Question 12: Penalties per rule

SELECT RULENUM,
       PENALTY,
       COUNT(*) AS PENALTY_COUNT
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
GROUP BY RULENUM, PENALTY;



-- Question 13: Ticket turnaround time (closed tickets)

SELECT AVG(DATEUPDATED - DATESUBMITTED) AS AVG_TIME,
       MAX(DATEUPDATED - DATESUBMITTED) AS MAX_TIME,
       MIN(DATEUPDATED - DATESUBMITTED) AS MIN_TIME
FROM TICKETS
WHERE STATUS = 'CLOSED';



-- Question 14: NEW tickets issue count

SELECT EMAIL,
       ISSUE,
       COUNT(*) AS ISSUE_COUNT
FROM TICKETS
WHERE STATUS = 'NEW'
GROUP BY EMAIL, ISSUE, DATESUBMITTED
ORDER BY ISSUE_COUNT;



-- Question 15: Users with firstname or lastname in password

SELECT USERID,
       FIRSTNAME,
       LASTNAME
FROM USERBASE
WHERE LOWER(PASSWORD) LIKE LOWER('%' || FIRSTNAME || '%')
   OR LOWER(PASSWORD) LIKE LOWER('%' || LASTNAME || '%');



-- Question 16: Average price per publisher

SELECT PUBLISHER,
       AVG(PRICE) AS AVG_PRICE
FROM PRODUCTS
GROUP BY PUBLISHER
ORDER BY PUBLISHER;



-- Question 17: View of discounted old products

CREATE OR REPLACE VIEW view_discounted_products AS
SELECT PRODUCTNAME,
       PRICE * 0.75 AS DISCOUNTED_PRICE
FROM PRODUCTS
WHERE RELEASEDATE < ADD_MONTHS(SYSDATE, -60);



-- Question 18: Max and Min price per genre

SELECT GENRE,
       MAX(PRICE) AS MAX_PRICE,
       MIN(PRICE) AS MIN_PRICE
FROM PRODUCTS
GROUP BY GENRE;



-- Question 19: View of chat logs from last week to now

CREATE OR REPLACE VIEW view_recent_chatlog AS
SELECT *
FROM CHATLOG
WHERE DATESENT BETWEEN SYSDATE - 7 AND SYSDATE;



-- Question 20: View of recent penalties (last month)

CREATE OR REPLACE VIEW view_recent_penalties AS
SELECT USERID,
       DATEASSIGNED,
       PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);